<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $page->product_name }}</title>
    <link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600,700,800&display=swap" rel="stylesheet" />
    <style>body { font-family: 'Figtree', system-ui, sans-serif; }</style>
</head>
<body class="antialiased">
    @include('sales_pages.partials.landing', ['page' => $page])
    <footer class="bg-gray-900 text-gray-400 text-center py-6 text-xs">
        Generated by AI Sales Page Generator · {{ now()->format('Y-m-d') }}
    </footer>
</body>
</html>
